services:
  app:
    image: bruckabey/vgrip:latest
    container_name: vgrip-app

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/vgrip

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16

    container_name: vgrip-postgres

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vgrip

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: